const Banner = require("./assets/banner_system/main.js");
console.log("\033[8;30;80t");
console.log("\x1b[44m");
/*console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");*/
console.log(Banner.ModifyBanner("main"));
console.log("                                                                               ");
console.log("                           \x1b[31mWelcome To Syntax V5.0.0                                                    ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
console.log("                                                                               ");
